title: Kris's playground
author: KrisYu
description: Just have some fun here
avatar: /images/avatar.png

# Build Settings
markdown: kramdown
# highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]
