title: Walter's Blog
author: Walter Wang
description: machine learning musings
avatar: /images/avatar.png

# Build Settings
markdown: kramdown
# highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# comments
# disqus:
#  shortname: http-walter-github-io

# Google Analytics
# google_analytics: UA-101189927-1
